//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Томск
{
    using System;
    using System.Collections.Generic;
    
    public partial class Washing
    {
        public int IDWahsing { get; set; }
        public string WashingStatus { get; set; }
        public Nullable<bool> DryingHeaving { get; set; }
        public Nullable<int> Powder { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Machines Machines { get; set; }
        public virtual Powders Powders { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
